# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jso/gitrepo/aiworld/cpp/V1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jso/gitrepo/aiworld/cpp/V1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jso/gitrepo/aiworld/cpp/V1/CMakeFiles /Users/jso/gitrepo/aiworld/cpp/V1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jso/gitrepo/aiworld/cpp/V1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gui

# Build rule for target.
gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gui
.PHONY : gui

# fast build rule for target.
gui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/build
.PHONY : gui/fast

#=============================================================================
# Target rules for targets named servidor

# Build rule for target.
servidor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 servidor
.PHONY : servidor

# fast build rule for target.
servidor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/build
.PHONY : servidor/fast

#=============================================================================
# Target rules for targets named cliente

# Build rule for target.
cliente: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cliente
.PHONY : cliente

# fast build rule for target.
cliente/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/build
.PHONY : cliente/fast

Client.o: Client.cpp.o
.PHONY : Client.o

# target to build an object file
Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/Client.cpp.o
.PHONY : Client.cpp.o

Client.i: Client.cpp.i
.PHONY : Client.i

# target to preprocess a source file
Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/Client.cpp.i
.PHONY : Client.cpp.i

Client.s: Client.cpp.s
.PHONY : Client.s

# target to generate assembly for a file
Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/Client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/Client.cpp.s
.PHONY : Client.cpp.s

PerlinNoise.o: PerlinNoise.cpp.o
.PHONY : PerlinNoise.o

# target to build an object file
PerlinNoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/PerlinNoise.cpp.o
.PHONY : PerlinNoise.cpp.o

PerlinNoise.i: PerlinNoise.cpp.i
.PHONY : PerlinNoise.i

# target to preprocess a source file
PerlinNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/PerlinNoise.cpp.i
.PHONY : PerlinNoise.cpp.i

PerlinNoise.s: PerlinNoise.cpp.s
.PHONY : PerlinNoise.s

# target to generate assembly for a file
PerlinNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/PerlinNoise.cpp.s
.PHONY : PerlinNoise.cpp.s

Personaje.o: Personaje.cpp.o
.PHONY : Personaje.o

# target to build an object file
Personaje.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/Personaje.cpp.o
.PHONY : Personaje.cpp.o

Personaje.i: Personaje.cpp.i
.PHONY : Personaje.i

# target to preprocess a source file
Personaje.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/Personaje.cpp.i
.PHONY : Personaje.cpp.i

Personaje.s: Personaje.cpp.s
.PHONY : Personaje.s

# target to generate assembly for a file
Personaje.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/Personaje.cpp.s
.PHONY : Personaje.cpp.s

World.o: World.cpp.o
.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i
.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s
.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/World.cpp.s
.PHONY : World.cpp.s

cliente3.o: cliente3.cpp.o
.PHONY : cliente3.o

# target to build an object file
cliente3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/cliente3.cpp.o
.PHONY : cliente3.cpp.o

cliente3.i: cliente3.cpp.i
.PHONY : cliente3.i

# target to preprocess a source file
cliente3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/cliente3.cpp.i
.PHONY : cliente3.cpp.i

cliente3.s: cliente3.cpp.s
.PHONY : cliente3.s

# target to generate assembly for a file
cliente3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cliente.dir/build.make CMakeFiles/cliente.dir/cliente3.cpp.s
.PHONY : cliente3.cpp.s

gui2.o: gui2.cpp.o
.PHONY : gui2.o

# target to build an object file
gui2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui2.cpp.o
.PHONY : gui2.cpp.o

gui2.i: gui2.cpp.i
.PHONY : gui2.i

# target to preprocess a source file
gui2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui2.cpp.i
.PHONY : gui2.cpp.i

gui2.s: gui2.cpp.s
.PHONY : gui2.s

# target to generate assembly for a file
gui2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gui.dir/build.make CMakeFiles/gui.dir/gui2.cpp.s
.PHONY : gui2.cpp.s

server3.o: server3.cpp.o
.PHONY : server3.o

# target to build an object file
server3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/server3.cpp.o
.PHONY : server3.cpp.o

server3.i: server3.cpp.i
.PHONY : server3.i

# target to preprocess a source file
server3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/server3.cpp.i
.PHONY : server3.cpp.i

server3.s: server3.cpp.s
.PHONY : server3.s

# target to generate assembly for a file
server3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/servidor.dir/build.make CMakeFiles/servidor.dir/server3.cpp.s
.PHONY : server3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cliente"
	@echo "... gui"
	@echo "... servidor"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... PerlinNoise.o"
	@echo "... PerlinNoise.i"
	@echo "... PerlinNoise.s"
	@echo "... Personaje.o"
	@echo "... Personaje.i"
	@echo "... Personaje.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
	@echo "... cliente3.o"
	@echo "... cliente3.i"
	@echo "... cliente3.s"
	@echo "... gui2.o"
	@echo "... gui2.i"
	@echo "... gui2.s"
	@echo "... server3.o"
	@echo "... server3.i"
	@echo "... server3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

